### ISSUE TITLE
selection appears on the opposite side on the x direction

### ISSUE THREAD

**Issue by cakirburak** [vmedea/kritaCellBasedSelection#1]
For example I have a canvas 100x100 with tiles 10x10. When I select tile {0, 0} ("{x, y}"). selection appares at {9, 0}.
When I select tile {4, 6}, selection appares at {5, 6}.

**Comment by cakirburak** [comment]
The layer I was woriking on somehow inverted on the x dir so, thats why it happened. Not an issue.

**Comment by vmedea** [comment]
Thanks for your report anyway! Happy to see anyone besides me is using this :)

-------- Oorspronkelijk bericht --------
Op 10-04-2024 18:33, schreef Burak Çakır :
